const gods = [
	{
		id: 1,
		is_own: 0,
		img: '../../static/img/gods/rulai',
		pname: '../../static/img/gods/shijiamoni.png'
	},
	{
		id: 2,
		is_own: 0,
		img: '../../static/img/gods/milefo',
		pname: '../../static/img/gods/milefo.png'
	},
	{
		id: 3,
		is_own: 0,
		img: '../../static/img/gods/guanyin',
		pname: '../../static/img/gods/guanyin.png'
	},
	{
		id: 4,
		is_own: 0,
		img: '../../static/img/gods/caishen',
		pname: '../../static/img/gods/wulucaishen.png'
	},
	{
		id: 5,
		is_own: 0,
		img: '../../static/img/gods/yaoshifo',
		pname: '../../static/img/gods/yaoshifo.png'
	},
	{
		id: 6,
		is_own: 0,
		img: '../../static/img/gods/guangong',
		pname: '../../static/img/gods/guangong.png'
	},
]

const godDict = {
	1: {
		id: 1,
		name: '释迦牟尼（如来佛祖）',
		img: '../../static/img/pray/gods/rulai_daxiang.png',
	},
	2: {
		id: 2,
		name: '弥勒佛',
		img: '../../static/img/pray/gods/milefo_daxiang.png',
	},
	3: {
		id: 3,
		name: '观音大士',
		img: '../../static/img/pray/gods/guanyin_daxiang.png',
	},
	4: {
		id: 4,
		name: '五路财神',
		img: '../../static/img/pray/gods/wulucaishen_daxiang.png',
	},
	5: {
		id: 5,
		name: '药师佛',
		img: '../../static/img/pray/gods/yaoshifo_daxiang.png',
	},
	6: {
		id: 6,
		name: '关公',
		img: '../../static/img/pray/gods/guangong_daxiang.png',
	}
}

const flowers = [
	{
		id: 13,
		price: 100,
		type: 3,
		name: '大莲花灯',
		pic: '../../static/img/pray/goods/offer/pingzi/dalianhuadeng.png',
	},
	{
		id: 16,
		price: 100,
		type: 3,
		name: '荷花',
		pic: '../../static/img/pray/goods/offer/pingzi/hehua.png',
	},
	{
		id: 14,
		price: 100,
		type: 3,
		name: '金莲',
		pic: '../../static/img/pray/goods/offer/pingzi/jinlian.png',
	},
	{
		id: 15,
		price: 100,
		name: '兰花',
		pic: '../../static/img/pray/goods/offer/pingzi/lanhua.png',
	},
	{
		id: 12,
		price: 100,
		type: 3,
		name: '小莲花灯',
		pic: '../../static/img/pray/goods/offer/pingzi/xiaolianhuadeng.png',
	},
]

const zhiqian = [
	{
		id: 1,
		price: 100,
		type: 1,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqianyi.png',
		name: '纸钱1',
		time: 1,
	},
	{
		id: 2,
		price: 100,
		type: 1,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqianer.png',
		name: '纸钱2',
		time: 2,
	},
	{
		id: 3,
		price: 100,
		type: 1,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqiansan.png',
		name: '纸钱3',
		time: 3,
	},
	{
		id: 4,
		price: 100,
		type: 1,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqiansi.png',
		name: '纸钱4',
		time: 4,
	},
	{
		id: 5,
		type: 1,
		price: 100,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqianwu.png',
		name: '纸钱5',
		time: 5,
	},
]

const diezi = [
	{
		id: 26,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/fotouguo.png',
		name: '佛头果',
		time: 1,
	},
	{
		id: 27,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/renshenguo.png',
		name: '人参果',
		time: 2,
	},
	{
		id: 28,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/li.png',
		name: '梨',
		time: 3,
	},
	{
		id: 23,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/pingguo.png',
		name: '苹果',
		time: 4,
	},
	{
		id: 25,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/putao.png',
		name: '葡萄',
		time: 5,
	},
	{
		id: 24,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/taozi.png',
		name: '桃子',
		time: 5,
	},
]

const xiang = [
	{
		id: 17,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/pinganxiang.png',
		name: '平安香',
		time: 5,
	},
	{
		id: 19,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/xiaozaixiang.png',
		name: '消灾香',
		time: 5,
	},
	{
		id: 18,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/zengcaixiang.png',
		name: '增财香',
		time: 5,
	},
	{
		id: 22,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/zengfuxiang.png',
		name: '增福香',
		time: 5,
	},
	{
		id: 20,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/zengyuanxiang.png',
		name: '增缘香',
		time: 5,
	},
	{
		id: 21,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/zhihuixiang.png',
		name: '智慧香',
		time: 5,
	},
]

const zhutai = [
	{
		id: 6,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/pinganzhu.png',
		name: '平安烛',
		time: 5,
	},
	{
		id: 8,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/xiaozaizhu.png',
		name: '消灾烛',
		time: 5,
	},
	{
		id: 7,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/zengcaizhu.png',
		name: '增财烛',
		time: 5,
	},
	{
		id: 11,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/zengfuzhu.png',
		name: '增福烛',
		time: 5,
	},
	{
		id: 9,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/zengyuanzhu.png',
		name: '增缘烛',
		time: 5,
	},
	{
		id: 10,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/zhihuizhu.png',
		name: '智慧烛',
		time: 5,
	},
]

export const init = [
	{
		id: 6,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/pinganzhu.png',
		name: '平安烛',
		time: 5,
	},
	{
		id: 8,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/xiaozaizhu.png',
		name: '消灾烛',
		time: 5,
	},
	{
		id: 7,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/zengcaizhu.png',
		name: '增财烛',
		time: 5,
	},
	{
		id: 11,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/zengfuzhu.png',
		name: '增福烛',
		time: 5,
	},
	{
		id: 9,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/zengyuanzhu.png',
		name: '增缘烛',
		time: 5,
	},
	{
		id: 10,
		type: 2,
		price: 100,
		pic: '../../static/img/pray/goods/offer/lazhu/zhihuizhu.png',
		name: '智慧烛',
		time: 5,
	},
	{
		id: 17,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/pinganxiang.png',
		name: '平安香',
		time: 5,
	},
	{
		id: 19,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/xiaozaixiang.png',
		name: '消灾香',
		time: 5,
	},
	{
		id: 18,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/zengcaixiang.png',
		name: '增财香',
		time: 5,
	},
	{
		id: 22,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/zengfuxiang.png',
		name: '增福香',
		time: 5,
	},
	{
		id: 20,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/zengyuanxiang.png',
		name: '增缘香',
		time: 5,
	},
	{
		id: 21,
		type: 4,
		price: 100,
		pic: '../../static/img/pray/goods/offer/xiang/zhihuixiang.png',
		name: '智慧香',
		time: 5,
	},
	{
		id: 26,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/fotouguo.png',
		name: '佛头果',
		time: 1,
	},
	{
		id: 27,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/renshenguo.png',
		name: '人参果',
		time: 2,
	},
	{
		id: 28,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/li.png',
		name: '梨',
		time: 3,
	},
	{
		id: 23,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/pingguo.png',
		name: '苹果',
		time: 4,
	},
	{
		id: 25,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/putao.png',
		name: '葡萄',
		time: 5,
	},
	{
		id: 24,
		type: 5,
		price: 100,
		pic: '../../static/img/pray/goods/offer/diezi/taozi.png',
		name: '桃子',
		time: 5,
	},
	{
		id: 1,
		price: 100,
		type: 1,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqianyi.png',
		name: '纸钱1',
		time: 1,
	},
	{
		id: 2,
		price: 100,
		type: 1,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqianer.png',
		name: '纸钱2',
		time: 2,
	},
	{
		id: 3,
		price: 100,
		type: 1,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqiansan.png',
		name: '纸钱3',
		time: 3,
	},
	{
		id: 4,
		price: 100,
		type: 1,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqiansi.png',
		name: '纸钱4',
		time: 4,
	},
	{
		id: 5,
		type: 1,
		price: 100,
		pic: '../../static/img/pray/goods/offer/zhiqian/zhiqianwu.png',
		name: '纸钱5',
		time: 5,
	},
	{
		id: 13,
		price: 100,
		type: 3,
		name: '大莲花灯',
		pic: '../../static/img/pray/goods/offer/pingzi/dalianhuadeng.png',
	},
	{
		id: 16,
		price: 100,
		type: 3,
		name: '荷花',
		pic: '../../static/img/pray/goods/offer/pingzi/hehua.png',
	},
	{
		id: 14,
		price: 100,
		type: 3,
		name: '金莲',
		pic: '../../static/img/pray/goods/offer/pingzi/jinlian.png',
	},
	{
		id: 15,
		price: 100,
		name: '兰花',
		pic: '../../static/img/pray/goods/offer/pingzi/lanhua.png',
	},
	{
		id: 12,
		price: 100,
		type: 3,
		name: '小莲花灯',
		pic: '../../static/img/pray/goods/offer/pingzi/xiaolianhuadeng.png',
	},
]

export default{
	gods,
	godDict,
	flowers,
	zhiqian,
	diezi,
	xiang,
	zhutai,
	init,
}